import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { ReactComponent as PhotoshopSVG } from '../public/icons/adobephotoshop.svg'
import { ReactComponent as ComplexSVG } from '../public/icons/complexicon.svg'
import { IconColor, IconSize } from './icon.config'
import cn from 'classnames'


const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className={styles.list}>
          <h2>Sizing</h2>
          <div>
            <PhotoshopSVG className={IconSize.S} />
            <code>{'<Icon className={IconSize.S} />'}</code>
          </div>
          <div>
            <PhotoshopSVG className={IconSize.M} />
            <code>{'<Icon className={IconSize.M} />'}</code>
          </div>
          <div>
            <PhotoshopSVG className={IconSize.L} />
            <code>{'<Icon className={IconSize.L} />'}</code>
          </div>
        </div>
        <div className={styles.list}>
          <h2>Filling</h2>
          <div>
            <PhotoshopSVG className={IconSize.M} fill="blue" />
            <code>{'<Icon fill="blue" />'}</code>
          </div>
          <div>
            <PhotoshopSVG className={IconSize.M} fill="red" />
            <code>{'<Icon fill="red" />'}</code>
          </div>
          <div>
            <PhotoshopSVG className={cn(IconSize.M, IconColor.PRIMARY)} />
            <code>{'<Icon className={IconColor.PRIMARY} />'}</code>
          </div>
          <div>
            <PhotoshopSVG className={cn(IconSize.M, IconColor.SECONDARY)} />
            <code>{'<Icon className={IconColor.SECONDARY} />'}</code>
          </div>
        </div>
        <div className={styles.list}>
          <h2>Complex icons</h2>
          <div>
            <ComplexSVG />
            <code>{'<Icon />'}</code>
          </div>
          <div>
            <ComplexSVG className={styles.complexIcon} />
            <code>{'<Icon className="my-complex-icon" />'}</code>
          </div>
        </div>
        <div>
          <h2>What do we need?</h2>
          <ol>
            <li>Add babel-plugin-inline-react-svg</li>
            <li>Add svgs to repo</li>
            <li>Prepare reusable configs for icons</li>
          </ol>
        </div>
        <div>
          <h2>Why?</h2>
          <ol>
            <li>Do not need to test and support another project</li>
            <li>Do not need to present svg file as tsx file</li>
            <li>Easier usage: just copy image to project. No need in extra scripting</li>
          </ol>
        </div>
      </main>
    </div>
  )
}

export default Home
